Repository vitruv-tools/Maven-Build-Parent, pull requests merged in 2022-08, with the labels that each got.

#30 Set generic developer based on mailing list as correspondence in pom
  pom.xml
Labels: minor

#29 Prepare CI for new branch management regarding releases
  .github/PULL_REQUEST_TEMPLATE/major.yaml
  .github/PULL_REQUEST_TEMPLATE/minor.yaml
  .github/workflows/ci.yml
  README.md
  pom.xml
Labels: enhancement

#31 Specify Codeowners
  .github/CODEOWNERS
Labels: minor

#36 Revert Spotless (pull request #23)
  .gitignore
  .mvn/jvm.config
  formatter.xml
  pom.xml
  spotless.importorder
Labels: major

#35 Perform tests as non-platform tests by default
  README.md
  pom.xml
Labels: major

#38 Releases/2.0.0
  .gitattributes
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/ci.yml
  README.md
  pom.xml
Labels: major

#40 Update version to 2.1.0-SNAPSHOT
  pom.xml
Labels: major

#44 Merge 2.0.1 into development branch
  pom.xml
Labels: patch

#45 Support aarch mac
  pom.xml
Labels: patch
